### ISSUE TITLE
Display fancy graphics in colour

### ISSUE THREAD

**Issue by robot-army** [robot-army/hotstick#15]

**Comment by Gavatastic** [comment]
compatible with a range of displays (to avoid obsolescence if screen component no longer available) [if Arduino based, something like Adafruit's GFX library?]

**Comment by daubers** [comment]
How about http://www.adafruit.com/products/358

**Comment by robot-army** [comment]
Should we steer away from specific details of implementation for the
moment? What's good about that specific part? Let's capture those good bits
in requirements, and figure out how to implement them in the design stage
of the project yeah?

**Comment by Remulos** [comment]
In that case one of the requirements for the display, as well as the rest of the device, needs to be the simplicity of it's programming. If the main target market is hobbyists and hackspaces then hack-ability is a requirements and some obsucre display which requires an equally obscure driver isn't ideal. Something like the Adafruit library is accesable to all and already comes with loads of online reseources.

**Comment by robot-army** [comment]
Yep, happy with that additional requirement. I'm sure whatever we end up
choosing won't be esoteric... we do want to be able to make this work,
after all!
