### ISSUE TITLE
ambient light detection for shutdown

### ISSUE THREAD

**Issue by dhprice** [robot-army/hotstick#20]
Detect when there is no ambient light (LDR) and shutdown the iron (capturing Bob's requirement from the earlier email thread)

**Comment by robot-army** [comment]
Good shout, thanks David.

**Comment by Gavatastic** [comment]
Mounted in a way that

**Comment by Gavatastic** [comment]
Mounted so that it is not triggered by the screen

**Comment by Remulos** [comment]
This is a good idea.

**Comment by dhprice** [comment]
Requirement is avoiding violations of rule zero. Possibly satisfied by detecting lack of handle motion, etc.
