### ISSUE TITLE
What power tip?

### ISSUE THREAD

**Issue by dhprice** [robot-army/hotstick#23]
Should this be 25, 40, 50watt?

I would prefer a platform that that is structured and hackable to accomodate a range of tips and power requirements. But what should the reference design be as this will in turn dictate component ratings and DC PSU requirements.

**Comment by robot-army** [comment]
The Weller tips need 40 watts, but driving them slightly harder sometimes
might be interesting to try.

**Comment by dhprice** [comment]
55 watts or whatever the tips use. New requirement needed to define.
