### ISSUE TITLE
Provide an SD card slot

### ISSUE THREAD

**Issue by Gavatastic** [robot-army/hotstick#27]
Collect data on how it is used (temps/duration) to better understand why rLab solder stations have limited life

**Comment by robot-army** [comment]
Totally, this is part of measuring and recording current.

**Comment by Remulos** [comment]
What sort of range would you want to store? Full lifecycle stats (i.e. 10,000 uses or something) might exceed basic micro controller memory.

**Comment by dhprice** [comment]
£2.50 or so for an ESP8266 WiFi serial interface ... you could store the 
data anywhere you like.

**Comment by Remulos** [comment]
If we're putting wireless in this thing then we'll have to look at some extra compliance requirements so we should figure this one out soon.

**Comment by robot-army** [comment]
Oh man, intentional radiators :)

I'd much rather an SD card or something

**Comment by robot-army** [comment]
but again, implementation is not for now. If we want to store stuff, we can
make it a requirement and figure out how to implement it 'soon'.

**Comment by Gavatastic** [comment]
Need not take to much memory if we're only storing and adjusting aggregate stats. The key thing would be to decide which one - no of usages, duty rate, length of low power periods ie are people just lazily leaving it on etc (not an expert on what would be best)

I like the idea of transmitting them for storage elsewhere, but think it's probably a lower priority requirement?

-----Original Message-----

**Comment by robot-army** [comment]
I really don't like the idea of wireless transmissions if we're going to
try to get this thing past any real compliance or type approval testing.

I'm not saying that we definitely WILL, but designing that in will make it
potentially a LOT more difficult if we do.

**Comment by Remulos** [comment]
I have to agree, I like wireless in everything as much as the next guy but working for UL means I know how much of a complete pain in the arse it can be and I don't think it's worth it. SD card would work though.

**Comment by dhprice** [comment]
Remind me why do we need to get compliance approval for an open source 
design?

**Comment by Remulos** [comment]
If you intend to sell it you need compliance approval, regardless of the copyright or lack thereof. Licencing is not Regulation.

**Comment by robot-army** [comment]
Because I'd like a product that can be 'put in to service'.

In my opinion, one big thing that's missing from open-source hardware is
standards compliance.

It can be found in software (eg. POSIX), why not hardware?

**Comment by dhprice** [comment]
I fully understand that aspect, it was not made clear that the goal is 
to build a sellable product.

**Comment by robot-army** [comment]
To clarify "If you intend to sell it you need compliance approval" - Not
only if you intend to sell it, but if you intend to put it in to service. I
think that's the wording, there's not many exemptions.

**Comment by robot-army** [comment]
Here's a quote from (a biased) interpretation the machinery directive, not
sure if it applies to the applicable directives for this product but...

"The Directive and the European guidance makes it very clear that Machinery
built for own use must be CE marked"

http://www.cemarkingassociation.co.uk/machinery-built-for-own-use-ce-marking/

**Comment by robot-army** [comment]
Can we move this thread of discussion over to the compliance requirement
issue please?

**Comment by jeremypoulter** [comment]
There are versions of the ESP8266 modules that come pre-certified, but that
being said I think maybe an SD card would be more appropriate for this task.

**Comment by Remulos** [comment]
The end product would still need to be tested to the EMC standard EN 301 489-1

**Comment by dhprice** [comment]
V. nice to have.

**Comment by robot-army** [comment]
Hardware requirement is provide some removable data storage. Is this one accepted? I can't remember.

**Comment by jeremypoulter** [comment]
I think it was. This would also be really useful in the dev stage for
debugging as well.

**Comment by robot-army** [comment]
OK
