### ISSUE TITLE
Drive a single Weller eg. RT1 tip

### ISSUE THREAD

**Issue by robot-army** [robot-army/hotstick#6]

**Comment by robot-army** [comment]
Need more detail here: Current, voltage, connector and other physical interface details

**Comment by daubers** [comment]
I can't actually find anything about an RP1 tip???

**Comment by ribbotson** [comment]
Shouldn't this be an RT1 tip ?

**Comment by robot-army** [comment]
Must be a typo! Sorry!

http://www.apexhandtools.com/weller/PDFs/Weller%20WX%20brochure%20US.pdf
lists all the tips available for WXMP irons.

**Comment by plett** [comment]
http://dangerousprototypes.com/2012/02/27/weller-rt-type-tip-teardown-and-reverse-engineering/ (and http://dangerousprototypes.com/forum/viewtopic.php?f=19&t=3583 ) documents a teardown on a RT1 tip.

It apparently uses a 3-pin stereo headphone jack (unclear if 2.5mm or 3.5mm) for +v, GND and temp sense, with a k-type thermocouple which you read when power isn't being applied.

**Comment by robot-army** [comment]
The system needs to be able to drive these tips at the maximum power.
