### ISSUE TITLE
Allow adjustment of temperature setpoint by rotary encoder with detents

### ISSUE THREAD

**Issue by robot-army** [robot-army/hotstick#8]
The hardware should provide for adjustment of the temperature setpoint

**Comment by dhprice** [comment]
Digital vs analogue?
rotary encoder vs up/down buttons?
presets for different work profiles?

**Comment by robot-army** [comment]
Yep, all of that. Personally I'll always prefer a nice optical encoder. Maybe a few buttons for profiles as well? I don't really use them, even when present, but maybe that's just me.
