### ISSUE TITLE
System power input DC, 12-24 V with as common a connector as we can manage.

### ISSUE THREAD

**Issue by robot-army** [robot-army/hotstick#9]
The unit should be able to be powered off any worldwide standard mains supply

**Comment by dhprice** [comment]
are soldering irons AC to the tip or is it worth considering DC via a laptop brick?

**Comment by robot-army** [comment]
The Weller tips are 12 Volt DC to the tip. An external brick would be a
great approach, I think it'd likely be the best way actually, especially
given the requirement to design for compliance. Let's not worry too much
about implementation at this stage, this requirement was to exclude other
requirements like powering it off USB.
